version: '3'
services: 
  user-app:
    image: haridevelops/finalversionmoviecruiser:backendauth1-image
    restart: always
    network_mode: host
    ports:
     - 8089:8089
    expose:
     - 8089
    depends_on:
     - movie-mysql
  movie-app:
    image: haridevelops/finalversionmoviecruiser:backend-image
    restart: always
    network_mode: host
    ports:
     - 8082:8082
    expose:
     - 8082
    depends_on:
     - movie-mysql
  movie-mysql:
    image: mysql:5.5
    network_mode: host
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app_root
      MYSQL_PASSWORD: root123
      MYSQL_DATABASE: moviedb
  angular:
    image: haridevelops/finalversionmoviecruiser:angulardist-image
    network_mode: host
    container_name: angular-docker
    ports:
      - 4200:4200
